In [1]:
import numpy as np

In [3]:
a = np.zeros ((2, 4))

In [6]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.zeros ((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [7]:
np.full((2,3,4),9)

array([[[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]]])

In [8]:
np.empty((2,3,9))

array([[[9.20039017e-312, 9.20039050e-312, 2.49644249e-312,
         0.00000000e+000, 1.69484279e-319, 2.49644249e-312,
         0.00000000e+000, 9.20075188e-312, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 9.20073758e-312,
         2.47032823e-323, 6.95201306e-310, 2.02369289e-320,
         2.47032823e-323, 6.95201306e-310, 9.88131292e-324],
        [0.00000000e+000, 0.00000000e+000, 1.37611116e-318,
         0.00000000e+000,             nan, 0.00000000e+000,
         4.67296746e-307, 1.69121096e-306, 3.22649121e-307]],

       [[5.56296306e-307, 7.56599807e-307, 8.90104239e-307,
         9.34593493e-307, 6.23059726e-307, 1.69121096e-306,
         1.51318196e-306, 7.56599807e-307, 1.78021391e-306],
        [6.23057349e-307, 6.23053954e-307, 9.34609790e-307,
         8.45593934e-307, 9.34600963e-307, 1.86921143e-306,
         6.23061763e-307, 8.90104239e-307, 6.89804132e-307],
        [1.33512376e-306, 6.89806849e-307, 9.34609790e-307,
         1.69121096e-306, 1.05700

In [12]:
b =np.array([[1,2,3],[4,5,6]])

In [13]:
b.ndim

2

In [15]:
np.linspace(0,6,10)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        , 4.66666667, 5.33333333, 6.        ])

In [16]:
np.random.rand(2,4)

array([[0.91033386, 0.98469937, 0.49348157, 0.61234871],
       [0.26065882, 0.63562599, 0.17864985, 0.48344779]])

In [20]:
array_multi = np.array([[1,2,3,4],[5,6,7,8]])
print(array_multi.shape)
array_multi

(2, 4)


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
array_multi[1,:]

array([5, 6, 7, 8])

In [25]:
array_multi[0,3]

4

In [26]:
array_multi[:,2]

array([3, 7])

In [27]:
array1=np.arange(28)

In [28]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [33]:
array1.shape =(7,4)

In [34]:
array1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [35]:
array2 =array1.reshape(4,7)

In [36]:
array2[0,3]=17

In [37]:
array2

array([[ 0,  1,  2, 17,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27]])

In [38]:
array1.ravel()

array([ 0,  1,  2, 17,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])